name: sound-recog
channels:
  - conda-forge
dependencies:
  - flask>=1.1.2
  - pyaudio>=0.2.11
  - python=3.7.6
  - requests>=2.23.0
  - flake8
  - black
  - isort
  - werkzeug>=1.0.1
  - tensorflow>=1.13.1
  - keras>=2.3.1
  - librosa>=0.6.3
