name: sound-recog
channels:
  - conda-forge
dependencies:
  - flask>=1.1.2
  - portaudio>=19.6.0
  - pyaudio>=0.2.11
  - python=3.7.6
  - requests>=2.23.0
  - flake8
  - black
  - isort
  - numpy
  - keras>=2.3.1
  - werkzeug>=1.0.1
  - tensorflow>=1.13.1
  - librosa>=0.6.3
  - pandas
  - matplotlib
  - scikit-learn